### PR TITLE
Feat: zero-downtime reindex

### LINKED ISSUE #2: Feature proposal: zero-downtime reindex
Hi there,

We have, in a private repository, an implementation of zero-downtime OpenSearch reindex of a whole collection of documents coming from an external source (possibly a Django model). It's based on:
* Putting a suffix on a Document's OpenSearch index (e.g. a timestamp)
* Setting an OpenSearch index alias on the current Document's index
* Re-indexing (e.g. after a deployment that changes the Documents schema) on a new index while the current one is still live
* Swapping the index alias
* Deleting obsolete indices

Do you think such feature could be a part of this lib?

### PR DESCRIPTION
**Pull request by David-Guillot**
Fixes #2

### CODE REVIEW

**Comment by David-Guillot** [comment]
@qcoumes it's all yours 🤓

**Review by qcoumes — CHANGES_REQUESTED** [review]

**Comment by qcoumes** [comment]
I'll test it locally tonight, but it seems awesome!

**Comment by qcoumes** [comment]
After some testing, especially with the CLI, I have some additional comments:

### 1. I couldn't find any way to delete a version of an index.

### 2. I couldn't activate a new version after creating a non-versioned index:

<details>
  <summary>details</summary>
<pre><code>
(venv) qcoumes 04:34:38 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create
The following indices will be created:
        - event.
        - country.
        - continent.

Continue ? [y]es [n]o : y

Creating index 'event'... OK
Creating index 'country'... OK
Creating index 'continent'... OK
(venv) qcoumes 04:34:46 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch list
django_dummy_app
[X] country (0 documents)
[X] continent (0 documents)
[X] event (0 documents)
(venv) qcoumes 04:34:52 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create country --versioned
The following indices will be created:
        - country.

Continue ? [y]es [n]o : y

Creating index 'country--20220815023520291529'... OK
(venv) qcoumes 04:35:20 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch list
django_dummy_app
[X] continent (0 documents)
[X] country. Following index versions exist:
    - country--20220815023520291529  (0 documents)
[X] event (0 documents)
(venv) qcoumes 04:35:55 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --version country--20220815023520291529
The following indices will be activated:
        - country.

Continue ? [y]es [n]o : y

Activating index 'country'... Error (already exists)
exiting...
</code></pre>
</details>

But everything worked fine after deleting the initial index:

<details>
  <summary>details</summary>
<pre><code>
(venv) qcoumes 04:36:13 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index delete country
The following indices will be deleted:
        - country.

Continue ? [y]es [n]o : y

Deleting index 'country'... OK
(venv) qcoumes 04:41:48 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --version country--20220815023520291529
The following indices will be activated:
        - country.

Continue ? [y]es [n]o : y

Activating index 'country'... OK
(venv) qcoumes 04:41:51 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create country --versioned
The following indices will be created:
        - country.

Continue ? [y]es [n]o : y

Creating index 'country--20220815024201559619'... OK
(venv) qcoumes 04:42:01 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --version country--20220815024201559619
The following indices will be activated:
        - country.

Continue ? [y]es [n]o : y

Activating index 'country'... OK
</code></pre>
</details>

### 3. I can activate a version of another index that the one I'm targeting :

<details>
  <summary>details</summary>
<pre><code>
(venv) qcoumes 04:42:10 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create country --versioned
The following indices will be created:
        - country.

Continue ? [y]es [n]o : y

Creating index 'country--20220815024600610362'... OK
(venv) qcoumes 04:46:01 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch list
django_dummy_app
[ ] event
[ ] continent
[ ] country. Following index versions exist:
    - country--20220815024600610362  (0 documents)
(venv) qcoumes 04:46:09 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate continent --versioned country--20220815024600610362
usage: manage.py opensearch [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks]
                            {list,index,document} ...
manage.py opensearch: error: unrecognized arguments: country--20220815024600610362
(venv) qcoumes 04:46:27 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate continent --version country--20220815024600610362
The following indices will be activated:
        - continent.

Continue ? [y]es [n]o : y

Activating index 'continent'... OK
(venv) qcoumes 04:46:36 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch list
django_dummy_app
[X] continent (0 documents)
[ ] country. Following index versions exist:
    - country--20220815024600610362  (0 documents)
[ ] event
(venv) qcoumes 04:46:56 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch document index -i continent
The following documents will be indexed:
        - 5 Continent.

Continue ? [y]es [n]o : y

Indexing 5 Continent: OK          

5 Continent successfully indexed, 0 errors:

(venv) qcoumes 04:47:01 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch list
django_dummy_app
[ ] event
[X] continent (5 documents)
[ ] country. Following index versions exist:
    - country--20220815024600610362  (5 documents)
</code></pre>
</details>

I check ensuring the given version corresponds to the right index would be useful.

**Comment by David-Guillot** [comment]
Thanks for your feedback 👍 , I'll work on making things better in the next few days 😀

**Comment by David-Guillot** [comment]
@qcoumes I just pushed 4 fixup commits that answer all open questions:

* Deleting an Index version, with `--version` argument
* Activating or deleting versions only for the matching Index
* Allowing to set a custom Index version suffix, with fallback on timestamp
* Activating the new version only optionally when migrating

Have fun, but I'm not available until September :wink:

**Comment by qcoumes** [comment]
@David-Guillot Thanks for the update!

---

I still have an error if I have a non-versioned index and I try to activate another version without deleting the non-versioned one :

<details>
  <summary>details</summary>
<pre><code>
(venv) qcoumes 05:54:50 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create country --force
The following indices will be created:
        - country.

Creating index 'country'... OK


(venv) qcoumes 05:55:53 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index create country --versioned --suffix v1 --force
The following indices will be created:
        - country.

Creating index 'country--v1'... OK


(venv) qcoumes 05:56:19 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --version country--v1 --force
The following indices will be activated:
        - country.

Activating index 'country'... Error (already exists)
exiting...
</code></pre>
</details>
I tried to activate the non-versioned index, using either the name of the index as the version or no version at all, and both methods failed :

<details>
  <summary>details</summary>
<pre><code>
(venv) qcoumes 05:56:47 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --version country --force
The following indices will be activated:
        - country.

Traceback (most recent call last):
  File "/Users/qcoumes/Git/django-opensearch-dsl/manage.py", line 23, in <module>
    main()
  File "/Users/qcoumes/Git/django-opensearch-dsl/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/management/commands/opensearch.py", line 407, in handle
    options["func"](**options)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/management/commands/opensearch.py", line 142, in _manage_index
    index.activate_version(version)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/indices.py", line 65, in activate_version
    index = self.get_version(version_name)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/indices.py", line 45, in get_version
    raise ValueError(f"Index version '{version_name}' not found for Index '{self._name}'")
ValueError: Index version 'country' not found for Index 'country'


(venv) qcoumes 05:57:05 ~/Git/django-opensearch-dsl (feat--no-downtime-reindex) $ python3 manage.py opensearch index activate country --force
The following indices will be activated:
        - country.

Traceback (most recent call last):
  File "/Users/qcoumes/Git/django-opensearch-dsl/manage.py", line 23, in <module>
    main()
  File "/Users/qcoumes/Git/django-opensearch-dsl/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/management/commands/opensearch.py", line 407, in handle
    options["func"](**options)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/management/commands/opensearch.py", line 142, in _manage_index
    index.activate_version(version)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/indices.py", line 65, in activate_version
    index = self.get_version(version_name)
  File "/Users/qcoumes/Git/django-opensearch-dsl/django_opensearch_dsl/indices.py", line 45, in get_version
    raise ValueError(f"Index version '{version_name}' not found for Index '{self._name}'")
ValueError: Index version 'None' not found for Index 'country'
</code></pre>
</details>


I think the best way to fix this issue is always to treat an index as a version, even implicitly. The version being the name of the index itself, without any suffix. This should make the code cleaner (e.g. in the list command) and
avoid such weird edge cases.

---

I thought about the `migrate` command, and it really looks like the `python manage.py opensearch document index` command. The only difference is that the `document index` command allows filters and the `index migrate` allows the `--activate` flag.

Maybe they should be merged together in the `document index` command. This would also keep the separation between the `index` and `document` part of the commands clearer since currently, the `index migrate` command is mostly about documents.

---

To summarize, we would have the following commands :

* `python manage.py opensearch index create [indices] {--versioned {--suffix=SUFFIX}}`
  * Create the specified indices version (or all if none were specified).
  * If `--versioned` is set, use the given `SUFFIX` (if specified) to create a new version, use a timestamp otherwise.
  * For each index, if this is the first version created, activate it.
  * This basically does not change the current behavior if no `--versioned` was provided, but ensures that all interactions with the indices are handled the same since they all are "version".

* `python manage.py opensearch index activate [index] [version]`
  * Activate the given version on the given index. The version can be the name of the index itself (if it was created without `--versioned`).

* `python manage.py opensearch document index {-i,--indices=[version, ...]}`
    * Index the document on all activated versions by default, of the given versions (even if not activated).
    * This would not change the current behavior since the default activated versions are the names of the indices themselves.

And these should be enough to handle the versioning.

---

I'm open to discussion, especially since the management command is maybe the ugliest part of the code.

If you want we can talk about that over a call when you're back and available!

**Comment by qcoumes** [comment]
@David-Guillot Any update on this MR? I can take from where you stop if you don't have any more time to spend on this.

**Comment by David-Guillot** [comment]
> @David-Guillot Any update on this MR? I can take from where you stop if you don't have any more time to spend on this.

Hi @qcoumes , I'm not available this week but hopefully I will be by the end of September. I'm still motivated to work on this, and open to discuss your suggestions :wink:

**Comment by David-Guillot** [comment]
Hi @qcoumes , sorry for the loooong delay. I'll have some time to work on that next week, will you be available to discuss it a bit?

**Comment by qcoumes** [comment]
Sure, when are you available? You can join me at quentin@codoc.co, so as to not pollute this thread.

**Comment by David-Guillot** [comment]
@qcoumes I have some news about this PR.

Actually I don't think I'm going to implement what we talked about, because there are plenty of blind spots we didn't see at the time, like index deletion for example, which is a nightmare with current implementation when considering all indices as versions, leading to major refactoring.

I dug very deeply into the topic and here is what I think:
* `opensearch-dsl` (and now `opensearchpy`) `Document` class already exposes the ability to have multiple indices for the same Document subclass (for example [this](https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/document.py#L158-L166) is basically the same code I had written), so I think we should use it, but it would change this lib a lot, because it would make it all about documents while for now it's clearly indices-oriented (even the `document` CLI commands does its filtering on indices instead of documents)
* IMO this lib should not care about indices so much: once the index versioning through `Document` class abilities would be implemented, clearly `index create` and `index rebuild` commands would make no sense anymore, and the `index delete` command would feel awkward and should be re-implemented as `document delete-version` or something like that.

So here would be my plan:
* Remove the index management feature (as this lib is a high-level one, and at high-level it's all about documents, not indices)
* Implement creating index versions through Document class abilities (by adding a `document init` CLI command which would take care of the index naming and calling the `Document.init()` method, if I ever find how to reach `Document` class from this indices-oriented code)

What do you think?

**Comment by David-Guillot** [comment]
Closing this since a new implementation is coming.

**Pull request closed without merging**
