### PR TITLE
Add support for Django 4.0, remove useless Python/Django combinations

### PR DESCRIPTION
**Pull request by David-Guillot**
+ some cleanup on supported versions

### CODE REVIEW

**Comment by David-Guillot** [comment]
Sorry for the force-push, I forgot something the first time. Next time I'll open the PR as draft, and for this one I'm finished.

**Comment by qcoumes** [comment]
I obviously have nothing against adding supports to Django 4, but I'd prefer keeping the compatibility (and tests) for all Django 2.1+ versions, as long as it does not block the implementation of features.

I know that some of these versions are not TLS but some projects can't be upgraded easily.
Django 2.2 will not be supported after April and a lot of projects still use this version, I don't think choosing to drop supports for non-LTS versions is a good idea.

As for the MR itself, if you're changing the supported version, you also need to change the corresponding `README.md`  requirements section and badges (it seems already not up-to-date, indicating Django 2.0).

**Comment by qcoumes** [comment]
> 



> Sorry for the force-push, I forgot something the first time. Next time I'll open the PR as draft, and for this one I'm finished.

No problem, you can do whatever you want on your branches, as long as it's cleaned before merging

**Comment by David-Guillot** [comment]
I understand, thanks for the feedback. Let's move this PR to draft and separate adding support from removing support.

**Comment by David-Guillot** [comment]
What I wanted to achieve with this PR (apart from adding support for Django 4.0) was to reduce the CI matrix, making this project more energy-saving. This goal has been achieved by updating the CI matrix exclusions precisely according to Django's Python support for each Django release. We're good to go on my side ;)

**Comment by qcoumes** [comment]
I can understand the ecological argument, removing incompatible django/python versions seems like a good start.

**Comment by qcoumes** [comment]
Can you just update the `README.md`'s badge to  [Django 2.1+](#) (`[Django 2.1+](#)`) ?

And I'll merge immediately !

**Comment by David-Guillot** [comment]
Ah yes sorry. Done in a fixup commit, are you able to rebase directly when merging, or do you want me to do it?

**Comment by qcoumes** [comment]
Manually rebased 👍

**Pull request closed without merging**
